### ISSUE TITLE
the queue seems deadlock with latest changes,

### ISSUE THREAD

**Issue by davidxiao** [rodrigo-brito/ninjabot#126]
With latest code change, the priority queue seems deadlock when tested by running paperwallet example.

wrapping the below code block in anonymous function works, but not so sure it has other potential issues.
https://github.com/rodrigo-brito/ninjabot/blob/main/model/priorityqueue.go#L30-L35

Reckon it's not necessary to use priority queue at all for the bot? sorry maybe i could be wrong because i have limited knowledge yet. but what I can think of is, 

- the bot doesn't maintain items in the queue, even potentially it's possible to accumulate some, but it's because  the downstreams can not handle in time.

- with above concern, then in most cases, it will be not used as expected because no items in it, or even if there are occasionally, it's no point to maintain the order according to time?

- probably strategy controller is the place to maintain the queue if needed, but i think candles are maintained from onCandle as below, and it reckon be reliable?

https://github.com/rodrigo-brito/ninjabot/blob/main/strategy/controller.go#L34

It'll be great if you can pls share more thoughts  :)

Thanks very much

**Comment by rodrigo-brito** [comment]
Thanks for the report. I will do a check.

The priority queue is important manly for backtesting. I will give a simple example:

- We have 3 pairs of coins for trading: BTCUSDT, ETHUSDT, and GRTUSDT.
- We have 3 CSV input files:
  - BTCUSDT: from 2013 to 2022
  - ETHUSDT: from 2020 to 2021
  - GRTUST: from 2021 to 2022

We read all CSV feed at the same time and the bot does not have information about the interval. In order to respect the chronological order, we have to start the backtesing in the BTCUST until 2020, then, we have to include ETHUSDT from 2020 and stop in 2021, finally, include GRTUST in 2021 (because it is a new coin, we do not have necessary historical data)

In this way, priority queue will control the order of processing of candles mainly for the time and second for alphabetical order of pairs name.

Now, for the production mode. It helps to control high frequency trading (HFT), when we have many pairs active, it can create a bottleneck and process candles out of order.

**Comment by rodrigo-brito** [comment]
@davidxiao fixed

**Comment by davidxiao** [comment]
nice

**Comment by davidxiao** [comment]
Hi, @rodrigo-brito ,
   With 2nd consideration, I am wondering if it's better and easier to maintain to move the priority queue to back testing part? I reckon it's not consistent and uncertain even if it works sometimes for HFT for me with my limited knowledge.

Thanks

**Comment by rodrigo-brito** [comment]
I don't think it's worth removing, you'll still need a FIFO structure to control the input flow
